### ISSUE TITLE
PNG images are converted to JPG

### ISSUE THREAD

**Issue by lombard0** [r10s/deltachat-android#58]
When sending a screenshot from phone, delta converts png files (screenshots) to jpg format.
Is it possible to keep original file?

I'm using v0.1.21 and Blackberry OS 10.3.2.2836

**Comment by r10s** [comment]
You can send the uncompressed, original file using "Attach / File / Gallery - send images without compression".

The images are send "as is" then and shown as normal images for the receiver (for yourself, it is shown as a send "file") (due to issue #55 they may not be shown in high quality, but this is only a display problem, the full data are there).

![screenshot_20170323-161019](https://cloud.githubusercontent.com/assets/9800740/24254843/2e0d83a0-0fe4-11e7-8fff-3e233aa83aaf.png)

![screenshot_20170323-161028](https://cloud.githubusercontent.com/assets/9800740/24254852/32fcd320-0fe4-11e7-9cc6-b8a3ee8779ae.png)

**Comment by JRHaigh** [comment]
PNG screenshots that I've sent by sharing to Delta Chat are sent degraded as lossy JPEG ‘attachments’ (which, annoyingly, can't actually be _attached_ to any text). I can see clearly that it's not a display issue because looking for the ‘Chat: Photo’ emails in another email client, I see that the attachments are JPEG. Upon sending, the user should be asked whether they want the image to be degraded. Maybe have a ‘don't ask threshold’ option in settings, where messages upto the threshold are sent verbatim without question whereas for messages larger than the threshold, the user is warned of the size and asked whether it's acceptable to use lossy compression on the attachments. The default threshold could be 10MiB.

**Comment by r10s** [comment]
Yeah, I know about this and I will fix it as soon as I find some time for it (and when I'm the next time near to this code ;-)

**Comment by r10s** [comment]
Fixed, will be available in Delta Chat 0.1.33 then.

**Comment by JRHaigh** [comment]
Thanks for fixing this for PNGs. I have [filed a separate issue](https://github.com/r10s/deltachat-android/issues/84) about the general issue of unrequested multimedia degradation.
