### ISSUE TITLE
Cannot delete app data on CM13.0 (Android 6.0.1)

### ISSUE THREAD

**Issue by Neudrino** [r10s/deltachat-android#61]
Usually apps have a 2 button in app-info screen, which allow for "Clear cache" and "Clear data". The "clear data" button is missing for Delta chat, such that I cannot revert all configurations, e.g., to start a fresh test case for the app.

Besides, I cannot find the app install directory under /storage/emulated/0/Android/data , where most/all the other apps are installed to. Is this intended? Where is the app installed to? Maybe I can delete config files manually?

Thanks for your time!

**Comment by r10s** [comment]
Hi Neudrino, 

thank you for your post.

It is planned to add some more specific options (there should be a "Manage space" button at App info -> Storage), however, currently, they are not working.

For clear everything, for now, just uninstall and reinstall the whole app,

Regarding the app data: They're stored where the operating system tells us to do so. On my phone eg. at /data/user/0/com.b44t.messenger/files/ - without root access no one but Delta Chat can read this directory, however, this is by design as it may contain sensitive data.
(you can export anything using the "Share" or eg. "Save to downloads" options when long-clicking a message)

**Comment by r10s** [comment]
Delta Chat 0.1.33 will have the normal "Clean data" button, see https://github.com/r10s/deltachat-android/commit/b6f04755a08396cb9f5e80c382d2981222f73cef
